export default {
  //保存当前登录用户
  userInfo :[], 
  isLogin:0,
  //总价
  totalPrice: 0,
  //总数量
  totalMount: 0,
  goods: [    
    {
    id:2,
    name:'秘制虾尾',
    content:[
      {
        id:1,
        name:'招牌虾尾【小份】',
        price:59.8,
        img:'01.jpg',
      },
      {
        id:2,
        name:'秘制麻辣虾尾【中份】',
        price:82,
        img:'1233.jpg',
      },
      {
        id:3,
        name:'秘制蒜香虾尾【小份】',
        price:65.8,
        img:'1233.jpg',
      }
    ]
    },{
    id:3,
    name:'招牌龙虾',
    content:[
      {
        id:1,
        name:'爆款麻辣小龙虾6钱/只',
        price:4.38,
        img:'1233.jpg',
      },
      {
        id:2,
        name:'蒜香麻辣小龙虾8钱/只',
        price:6.89,
        img:'1233.jpg',
      },
      {
        id:3,
        name:'十三香麻辣小龙虾【小份8钱装】',
        price:118,
        img:'1233.jpg',
      },
      {
        id:4,
        name:'麻辣小龙虾【小份8钱装】',
        price:118,
        img:'1233.jpg',
      }
    ]
    },{
    id:4,
    name:'木炭烧烤',
    content:[
      {
        id:1,
        name:'碳烤牛肉小串【20串】',
        price:10.4,
        img:'1233.jpg',
      },
      {
        id:2,
        name:'风味羊肉串【100%真羊肉】',
        price:3,
        img:'1233.jpg',
      },
      {
        id:3,
        name:'碳烤五花小肉串【20份】',
        price:18.6,
        img:'1233.jpg',
      },
      {
        id:4,
        name:'碳烤鱿鱼小串【20份】',
        price:18.6,
        img:'1233.jpg',
      },
      {
        id:5,
        name:'碳烤土豆片',
        price:2,
        img:'1233.jpg',
      },
      {
        id:6,
        name:'碳烤鸡脆骨【20份】',
        price:17.6,
        img:'1233.jpg',
      },
      {
        id:7,
        name:'碳烤面筋【孜然】',
        price:5,
        img:'1233.jpg',
      },{
        id:8,
        name:'碳烤豆皮金针菇',
        price:3,
        img:'1233.jpg',
      },{
        id:9,
        name:'碳烤鱼豆腐',
        price:3,
        img:'1233.jpg',
      },{
        id:10,
        name:'蒜蓉黄金小扇贝',
        price:5,
        img:'1233.jpg',
      },{
        id:11,
        name:'碳烤韭菜【精选】',
        price:4,
        img:'1233.jpg',
      },
    ]
    },{
    id:5,
    name:'秘制闸蟹',
    content:[
      {
        id:1,
        name:'招牌虾尾',
        price:1111,
        img:'1233.jpg',
      },
      {
        id:2,
        name:'秘制麻辣扇贝肉',
        price:1111,
        img:'1233.jpg',
      },
      {
        id:3,
        name:'麻辣小龙虾',
        price:1111,
        img:'1233.jpg',
      },
      {
        id:4,
        name:'碳烤羊肉串',
        price:1111,
        img:'1233.jpg',
      },
      {
        id:5,
        name:'爆出麻辣花甲',
        price:1111,
        img:'1233.jpg',
      },
      {
        id:6,
        name:'爆炒田螺',
        price:1111,
        img:'1233.jpg',
      },
    ]
    },{
    id:6,
    name:'招牌川菜',
    content:[
      {
        id:1,
        name:'招牌虾尾',
        price:1111,
        img:'1233.jpg',
      },
      {
        id:2,
        name:'秘制麻辣扇贝肉',
        price:1111,
        img:'1233.jpg',
      },
      {
        id:3,
        name:'麻辣小龙虾',
        price:1111,
        img:'1233.jpg',
      },
      {
        id:4,
        name:'碳烤羊肉串',
        price:1111,
        img:'1233.jpg',
      },
      {
        id:5,
        name:'爆出麻辣花甲',
        price:1111,
        img:'1233.jpg',
      },
      {
        id:6,
        name:'爆炒田螺',
        price:1111,
        img:'1233.jpg',
      },
    ]
    },{
    id:7,
    name:'主食小吃',
    content:[
      {
        id:1,
        name:'招牌虾尾',
        price:1111,
        img:'1233.jpg',
      },
      {
        id:2,
        name:'秘制麻辣扇贝肉',
        price:1111,
        img:'1233.jpg',
      },
      {
        id:3,
        name:'麻辣小龙虾',
        price:1111,
        img:'1233.jpg',
      },
      {
        id:4,
        name:'碳烤羊肉串',
        price:1111,
        img:'1233.jpg',
      },
      {
        id:5,
        name:'爆出麻辣花甲',
        price:1111,
        img:'1233.jpg',
      },
      {
        id:6,
        name:'爆炒田螺',
        price:1111,
        img:'1233.jpg',
      },
    ]
    },{
    id:8,
    name:'酒水饮料',
    content:[
      {
        id:1,
        name:'招牌虾尾',
        price:1111,
        img:'1233.jpg',
      },
      {
        id:2,
        name:'秘制麻辣扇贝肉',
        price:1111,
        img:'1233.jpg',
      },
      {
        id:3,
        name:'麻辣小龙虾',
        price:1111,
        img:'1233.jpg',
      },
      {
        id:4,
        name:'碳烤羊肉串',
        price:1111,
        img:'1233.jpg',
      },
      {
        id:5,
        name:'爆出麻辣花甲',
        price:1111,
        img:'1233.jpg',
      },
      {
        id:6,
        name:'爆炒田螺',
        price:1111,
        img:'1233.jpg',
      },
    ]
    }
  ], // 商品列表
  cartFoods: [],
    //购物车中的商品信息
    // {
    //   id: 1,
    //   img: '',
    //   name: '',
    //   price: 1999,
    //   totalMount: 2,
    //   totalPrice: 1999 * 2
    // }
}